"""adicao da opção de apagar por cascata, ao apagar o projeto serão apagadas as metas vinculadas

Revision ID: 33df01c23e9b
Revises: 8ec132615996
Create Date: 2026-04-20 00:41:46.593080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33df01c23e9b'
down_revision = '8ec132615996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'projeto', ['projeto_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'projeto', ['projeto_id'], ['id'])

    # ### end Alembic commands ###
