"""adicao do campo de última edicao em projetos e metas

Revision ID: 8ec132615996
Revises: 05a0b42e0adf
Create Date: 2026-04-20 00:01:09.242218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec132615996'
down_revision = '05a0b42e0adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_edicao', sa.DateTime(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.BOOLEAN(),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('projeto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_edicao', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projeto', schema=None) as batch_op:
        batch_op.drop_column('data_edicao')

    with op.batch_alter_table('meta', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Text(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
        batch_op.drop_column('data_edicao')

    # ### end Alembic commands ###
